### ISSUE TITLE
Tool integrations

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MsCrmTools.MetadataBrowser#13]
Suggestion: Implement the IMessageBusHost interface to make it possible from another tool open MDB and highlight a specific object, e.g. a relationship, an entity or an attribute.

**Comment by MscrmTools** [comment]
@rappen, you know what? it is implemented in Metadata Browser Companion!
Yes, I know... You asked for this 4 years ago 😄

**Comment by rappen** [comment]
😁
