### ISSUE TITLE
Export to excel functionality not working. "Could not load file or assembly EPPlus"

### ISSUE THREAD

**Issue by alikrc** [MscrmTools/MsCrmTools.MetadataBrowser#15]
Hi, this is an easy to solve issue.

On metadatabrowser plugin, after clicking  export to excel button and selecting file location and name i get an missing dll error. Please add the following dll to dependencies

EPPlus v4.1.1.1

![image](https://user-images.githubusercontent.com/2185905/45617903-7e270e80-ba7c-11e8-9ac1-39c256e8a9d7.png)

**Comment by Edwin-VC** [comment]
Same finding. Based on earlier reported issue (April) this is an older problem. Could not find a quick solution. Love this tool, but rarely use the export function. If anyone has an idea?

**Comment by gileswood** [comment]
The package requires EPPlus from nuget.  I'm not certain of the correct procedure for installing nuget packages outside Visual Studio, but this worked for me:

1. Download EPPlus from https://www.nuget.org/packages/EPPlus/4.1.1, save it to the folder of your choice, and unblock it.  The file is named epplus.4.1.1.nupkg.
2. If like me you haven't already got nuget.exe, download it from https://www.nuget.org/downloads, put it into the same folder just as a temporary measure, and unblock it.
3. Launch Command prompt, change to the folder where you put the file, and run the following commands:
`nuget install EPPlus -Source %cd% -OutputDirectory %AppData%\MscrmTools\XrmToolBox\NugetPlugins`
`cd %AppData%\MscrmTools\XrmToolBox`
`copy NugetPlugins\lib\net40\EPPlus.dll Plugins\.`
4. Restart XrmToolBox
The files you downloaded can now be deleted.

Hope this helps!

**Comment by MscrmTools** [comment]
I will release a new version with epplus back in the package
