### ISSUE TITLE
Loading popup hanging

### ISSUE THREAD

**Issue by alikrc** [MscrmTools/MsCrmTools.MetadataBrowser#16]
Steps for reproduce:
1) Open xrmtoolbox.
2) Click Metadata Browser
3) Click yes on the organisation connection popup and choose one.
4) Wait metadatabrowser to load entities.
5) Loading popup does not hide ->
![image](https://user-images.githubusercontent.com/2185905/48194982-8bb39300-e35f-11e8-9e83-239998812ac9.png)

**Comment by MscrmTools** [comment]
I cannot reproduce but I guess it's more related to XrmToolBox than Metadata Browser itself

**Comment by alikrc** [comment]
> I cannot reproduce but I guess it's more related to XrmToolBox than Metadata Browser itself

It seems so, its not a major problem but annoying. After connection established popup must be hided somewhere. This bug was occured after the preloading entities of last session patch.
