### ISSUE TITLE
[Critical] Metadatabrowser giving exception at the load entities 

### ISSUE THREAD

**Issue by alikrc** [MscrmTools/MsCrmTools.MetadataBrowser#17]
Hi, getting this error at start of the metadatabrowser plugin.

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: The type RelationshipMetadataBase does not have a property named LogicalName (Fault Detail is equal to Exception details: 
ErrorCode: 0x80044183
Message: The type RelationshipMetadataBase does not have a property named LogicalName
TimeStamp: 2018-11-15T07:43:07.1550662Z
--
Exception details: 
ErrorCode: 0x80044183
Message: The type RelationshipMetadataBase does not have a property named LogicalName
TimeStamp: 2018-11-15T07:43:07.1550662Z

![image](https://user-images.githubusercontent.com/2185905/48537792-aa67db80-e8c3-11e8-9908-4e1eb2b29096.png)

**Comment by MscrmTools** [comment]
I thought I have fixed this before releasing the new version...
Let me check

**Comment by MscrmTools** [comment]
Version 1.2018.11.10 on its way...
