### ISSUE TITLE
Export to excel doesn't support space in file path

### ISSUE THREAD

**Issue by Splaxi** [MscrmTools/MsCrmTools.MetadataBrowser#18]
It seems that export the file to a file path with spaces work like expected, but when asked to have the file opened it fails.

![image](https://user-images.githubusercontent.com/8750181/59832257-baf1a000-9343-11e9-9c9d-e48dbf05dc8c.png)

Excel now starts and takes every part of the path that has a space, and tries to open the file.

I expect that you need to work with either single or double quotes to make sure that the entire path passed to excel is being opened.

https://github.com/MscrmTools/MsCrmTools.MetadataBrowser/blob/d2aa5a881ae9af1ec87793a979608fbebb5a3920/MsCrmTools.MetadataBrowser/AppCode/Excel/Builder.cs#L56

**Comment by MscrmTools** [comment]
Thank you, I will fix this
