### ISSUE TITLE
MultiSelect Option Set Attribute show wrong AttributeType in v.9.1

### ISSUE THREAD

**Issue by AngelRodriguez8008** [MscrmTools/MsCrmTools.MetadataBrowser#19]
MultiSelect Option Set Attribute are showing in Tool:
1. AttributeType as "Picklist" but it was "Virtual"
2. AttributeTypeName as "MultiSelect Picklist" but it was "MultiSelectPicklistType"

**Comment by MscrmTools** [comment]
I will need to check it because first version of v9 SDK was not exposing the correct type so it’s possible I added my own implementation here

**Comment by AngelRodriguez8008** [comment]
**I found it hier:**
Type: Microsoft.Xrm.Sdk.Metadata.AttributeTypeDisplayName
Assembly: Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
MVID: EAB2BB07-5F89-4A71-806F-AC820970845C
Assembly location: .nuget\packages\microsoft.crmsdk.coreassemblies\9.0.2.21\lib\net462\Microsoft.Xrm.Sdk.dll

`public static readonly AttributeTypeDisplayName MultiSelectPicklistType = ConstantsBase<string>.Add<AttributeTypeDisplayName>(nameof (MultiSelectPicklistType));`

[Documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.attributetypedisplayname.multiselectpicklisttype?view=dynamics-general-ce-9)

**Comment by MscrmTools** [comment]
Ok, so MetadataBrowser is just displaying info coming from SDK. So the SDK consider it as a virtual field.
Won't fix
