### ISSUE TITLE
Enhancement: Add button on Attribute to open Field settings

### ISSUE THREAD

**Issue by daggen** [MscrmTools/MsCrmTools.MetadataBrowser#2]
First, Great plugin!
It would be very helpful if it was possible to quick shift between your browser to be able to make changes to the system. One way could be to add buttons in the many to open the field settings page. (This would be helpful for entities as well.) If this is what the property page button does. Then it is not working for me as it is always deactivated.

Thanks!

**Comment by MscrmTools** [comment]
Hi, accepted! And almost ready to ship in a new release
