### ISSUE TITLE
Metadata Browser is best ever - how use it from other tools?

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MsCrmTools.MetadataBrowser#21]
I want to add metadata info in FXB.
But using PropertyGrid it requires a lot to show "more complex" objects. Like this...

![image](https://user-images.githubusercontent.com/2572253/133930195-103fdf32-838e-4314-85c6-9e521c63e32f.png)

Would it be any way to use anything from the codes/functions that has the awesome smarts?
Something like the `EntityPropertiesControl` https://github.com/MscrmTools/MsCrmTools.MetadataBrowser/blob/master/MsCrmTools.MetadataBrowser/UserControls/EntityPropertiesControl.cs

---
- Deployment: Online
- DB Version: 9.2.21084.141
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.9.52
- Tool Version: 1.2021.9.17

**Comment by MscrmTools** [comment]
Not sure what you are after, @rappen...
You can copy my code if you want to, no problem for me... 
The magic happens more on xxxInfo classes than in EntityPropertiesControl.
See the descriptors in xxxInfo classes here : https://github.com/MscrmTools/MsCrmTools.MetadataBrowser/tree/master/MsCrmTools.MetadataBrowser/AppCode

**Comment by rappen** [comment]
Well ok, maybe there's nothing for you to do.
And if I may sneak your codes, that does a lot.
I'm see what I can do!
