### ISSUE TITLE
Table 'Solution' tab

### ISSUE THREAD

**Issue by jschof** [MscrmTools/MsCrmTools.MetadataBrowser#24]
Please consider adding a tab that displays the list of solutions (and their info) that the entity is a member of.

This would be alongside the existing Columns, Keys, etc. tabs.

![image](https://user-images.githubusercontent.com/15448821/149177733-9cc4b4fc-8f08-4b8a-8da2-9c08f74736a1.png)

It work also be extremely helpful if one of the columns was the entity name.

**Comment by MscrmTools** [comment]
@jschof like this?
![image](https://user-images.githubusercontent.com/10774317/149187715-0906c7f3-9744-46c6-83e2-3823ba9a0c3d.png)

**Comment by jschof** [comment]
@MscrmTools Exactly!!! Really appreciate you looking at this so quickly.

Would it be possible to include the entity (table) name similar to how you did for the columns?

![image](https://user-images.githubusercontent.com/15448821/149192581-5d4711d4-c0b8-4b74-b2b8-b5c5a3c4e94d.png)

That way I could export the tab contents and have the proper (parent) context.

**Comment by MscrmTools** [comment]
That is possible.
The new version should be available tomorrow

**Comment by jschof** [comment]
Looking forward to testing it. Thanks again!

**Comment by MscrmTools** [comment]
This is available
