### ISSUE TITLE
Adding option set values to listviews

### ISSUE THREAD

**Issue by jschof** [MscrmTools/MsCrmTools.MetadataBrowser#27]
Please consider adding option set values to a column in both the Choices and Columns tab.

I know a panel already exists with this information but the idea would be to have a a single cell per row that contains a delimited list in the form of, for example, _(optionValue) optionLabel_ so:

1. This metadata could be included in the Excel export
2. The user could visualize the values for all rows (where applicable) without having to iterate through each row.

**Columns Tab Example**

![image](https://user-images.githubusercontent.com/15448821/173605314-9e8fb725-3964-4b43-923d-ab9ee0bcf6e3.png)

**Comment by MscrmTools** [comment]
The grid is purely generic and displays onlu y information common to all column types so I'm quite sure it won't be easy to do.
Let me check

**Comment by jschof** [comment]
Understood, thank you for looking into it nonetheless.
