### ISSUE TITLE
Metadata Browser fails to load on startup

### ISSUE THREAD

**Issue by pbojanczyk** [MscrmTools/MsCrmTools.MetadataBrowser#28]
After updating to the latest version of the plugin, Metadata Browser won't load properly.  Below is the message I receive.
![Qf6Z2HXYWs](https://user-images.githubusercontent.com/14302673/193638009-db5fed61-0685-4855-a803-1071edbb2fe4.png)
.

**Comment by MarkS2145** [comment]
I too had this issue this morning when upgrading to the new version.  I delete the new files... now how do I load a previous version as a short term work around "to keep on, keeping on"?

**Comment by MscrmTools** [comment]
Do you have latest version of XrmToolBox installed?

**Comment by pbojanczyk** [comment]
That was the issue.  For some reason XrmToolbox didn't prompt me about the new version and I had to manually force the update.
