### ISSUE TITLE
Feature request : Add aggregated columns to the display or to the excel export

### ISSUE THREAD

**Issue by sybaris** [MscrmTools/MsCrmTools.MetadataBrowser#30]
Hi,

Somme columns like CascadeConfiguration, in the data we have "(Open row to see details)".
So when we export to excel, we don't have the data...
I think that a good feature/improvement, should be to add these data availiable  in the table...

Regards
Sybaris

![image](https://user-images.githubusercontent.com/11009997/203997828-4b9fc7cc-e1ec-4b3c-8157-322915da9e26.png)

**Comment by MscrmTools** [comment]
@sybaris The best I can do here is to show a tooltip with the values
![image](https://user-images.githubusercontent.com/10774317/205333292-bf61bbff-f196-43bc-9b76-addb8f2c8280.png)

Would it fit your need?

**Comment by sybaris** [comment]
I understand, and thank you for your answer. 
However, my need is to be able to export this data... 
Thanks anyway...

**Comment by MscrmTools** [comment]
I was only talking about the UI. I added the export to excel too! 😁
A new release should be available in the next couple of hours
