### ISSUE TITLE
Search by GUID

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MsCrmTools.MetadataBrowser#4]
When you get solution import it is common to only get the GUID of the object in target environment that causes the problem.
Being able to search metadata objects by GUID would be great!

![image](https://user-images.githubusercontent.com/2572253/28960986-f1d1a930-7900-11e7-95ac-a40b4eb4e000.png)

![image](https://user-images.githubusercontent.com/2572253/28961107-66ad6cb2-7901-11e7-8429-e05b5fdd97b0.png)

Sample error:

``A managed solution cannot overwrite the Attribute component with Id=5b92a22f-c031-4eaf-8b98-df60eae3551f which has an unmanaged base instance.  The most likely scenario for this error is that an unmanaged solution has installed a new unmanaged Attribute component on the target system, and now a managed solution from the same publisher is trying to install that same Attribute component as managed.  This will cause an invalid layering of solutions on the target system and is not allowed.
``

**Comment by MscrmTools** [comment]
Easy to add! 
Now, I'm in holidays tomorrow so I cannot assure to add this soon

**Comment by rappen** [comment]
I might just ``--E`` it and do it myself... 😉
