### ISSUE TITLE
Unable to Remove Unnecessary Columns in Relationships of Entities

### ISSUE THREAD

**Issue by manas3487** [MscrmTools/MsCrmTools.MetadataBrowser#6]
Hi,
Below is the issue which I have faced during the usage of the XRM toolbox Metadata Browser.
I am unable to remove unnecessary columns from the browser when I open the relationships for a particular entity.
Attached below screen shot which will be more useful for understanding.
![issuerelationships](https://user-images.githubusercontent.com/35729553/35274730-3a481228-0063-11e8-9897-7c87fa4476ca.PNG)

Thanks and Regards,
Manas

**Comment by manas3487** [comment]
Actually it is not fixed

**Comment by MscrmTools** [comment]
Actually it is
![image](https://user-images.githubusercontent.com/10774317/38093587-bc242706-336b-11e8-8fbd-199a7a878fcb.png)

Please update to latest version  of MetadataBrowser and you will be able to filter out columns you don't want for relationships

**Comment by manas3487** [comment]
Hi I just updated my XRM toolbox and it seems I am uable to that
filtering.. In addition to that I have found one more bug like when I press
load entities in metadata browser the field names on the top are displaying
next to the original one again.
Please help in rectifying with the filtering and this issue as well.

Thanks
Manas

**Comment by MscrmTools** [comment]
This is not XrmToolBox that needs to be updated but the tool metadataBrowser itself.
Please use Plugins Store to update the plugin

**Comment by MscrmTools** [comment]
As for another bug, please create a new issue

**Comment by manas3487** [comment]
Thanks for your input I have updated my plugin and now its working fine

Thanks
Manas
