### ISSUE TITLE
[feature request] Connect to multiple organization

### ISSUE THREAD

**Issue by alikrc** [MscrmTools/MsCrmTools.MetadataBrowser#8]
Hi. I use metadata browser for multiple organizations. I use it like this:

1) Connect an organization.
2) Open the metadata plugin.
3) Connect another organization.
4) Open the metadata plugin in another tab(don't refresh other tabs)

So i had to connect between multiple organizations and i got 3 plugin tabs always open. İ change organization connection frequently. Connection times are wasting too much time.How can this plugin easily switched between organizations or extended to get the life easier for this scenario? I can work in this feature too.

**Comment by MscrmTools** [comment]
Ok, So I guess your feature request is more a request for XrmToolBox than for this plugin. It seems complicated to implement without lot of code rework. I will investigate to understand how this could be implemented.
I will close this issue and move it to XrmToolBox repository

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/XrmToolBox #747](https://github.com/MscrmTools/XrmToolBox/issues/747) via [**ZenHub**](https://www.zenhub.com/)
